### ISSUE TITLE
Probe behaviour: probe_handle_msg/2 or probe_handle_message/2?

### ISSUE THREAD

**Issue by blaketan** [discordapp/instruments#4]
Behaviour `Instruments.Probe` expects a callback `probe_handle_msg/2` to be defined (and this is implemented in the sample `Instruments.Probes.Schedulers` as well as in the probe tests), however the `handle_info` callback in `Instruments.Probe.Runner` GenServer calls the `probe_handle_message/2` function of the probe module.

**Comment by ihumanable** [comment]
There does appear to be a disagreement.

I've opened #8 to address this issue, please let me know if it seems reasonable to you.

**Comment by blaketan** [comment]
👍 Thanks for addressing this!

**Comment by zorkian** [comment]
Committed the fix, sorry that languished!
